--- 
climates: 
  - 
    name: mean_annual
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\prec_12_tif"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\tmean_12_tif"
  - 
    name: max_t_lgm_ccsm4
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - CCSM4\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - CCSM4\\tx"
  - 
    name: min_t_lgm_ccsm4
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - CCSM4\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - CCSM4\\tn"
  - 
    name: min_t_lgm_mpi
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MPI - ESM - P\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MPI - ESM - P\\tn"
  - 
    name: max_t_lgm_mpi
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MPI - ESM - P\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MPI - ESM - P\\tx"
  - 
    name: min_t_lgm_miroc
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MIROC-ESM\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MIROC-ESM\\tn"
  - 
    name: max_t_lgm_miroc
    precip_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MIROC-ESM\\pr"
    temp_directory: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Climate\\LGM - MIROC-ESM\\tx"
fault_path: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\dv_faults_normal.shp"
faults: 
  cluster_tolerance: 1.5
  search_radius: 20
flow_acc: 
  flow_data_type: INTEGER
  flow_weight_raster: ""
flow_dir: 
  force_flow: NORMAL
lithology_path: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\lithology.shp"
original_dem: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Death_Valley_UTM.tif"
output: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Output"
pour_points: 
  minimum_height: 35
  snap_distance: 30
pour_points_path: ""
project_name: death_valley
projection_code: 32611
root: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley"
scratch: "C:\\Users\\sb708\\Documents\\PhD Work\\GIS\\Death Valley\\Scratch"
set_null: 
  conditional: "VALUE = 0"
  false_raster: 1
str_net: 
  conditional: "VALUE > 300"
  false_constant: 0
str_ord: 
  method: STRAHLER
uplift_mm_yr: 0
